apiVersion: v1
kind: Namespace
metadata:
  name: spring-mantis
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: spring-mantis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: rapportDB
            - name: MYSQL_ROOT_HOST
              value: "%"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: spring-mantis
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  namespace: spring-mantis
spec:
  replicas: 5
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: yleymard/spring_mantis:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8787

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-app
  namespace: spring-mantis
spec:
  selector:
    app: springboot-app
  ports:
    - name: springboot-app
      protocol: TCP
      port: 8787
      targetPort: 8787
  type: LoadBalancer
  externalIPs: 
    - 192.168.47.137
  
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-ingress
  namespace: spring-mantis
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: api.burotopiris.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: springboot-app
                port:
                  number: 8787

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: spring-mantis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: mysql-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: spring-mantis
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: standard
  hostPath:
    path: /mnt/mysql-pv